export default {
	auth: {
		token: '/api/running-auth/oauth/token',
		logout: '/api/running-auth/oauth/logout',
		captcha: '/api/running-auth/oauth/captcha',
	},
	user: {
		page: '/api/running-user/page',
		submit: '/api/running-user/submit',
		remove: '/api/running-user/remove',
		update: '/api/running-user/update',
		enable: '/api/running-user/enable',
		stop: '/api/running-user/stop',
		updatePlatform: '/api/running-user/update-platform',
		detail: '/api/running-user/detail',
		platformDetail: '/api/running-user/platform-detail',
		info: '/api/running-user/info',
		resetPassword: '/api/running-user/reset-password',
		updatePassword: '/api/running-user/update-password',
		updateInfo: '/api/running-user/update-info',
		grant: '/api/running-user/grant',
		unlock: '/api/running-user/unlock',
	},
	dept: {
		list: '/api/running-system/dept/list',
		lazyList: '/api/running-system/dept/lazy-list',
		detail: '/api/running-system/dept/detail',
		tree: '/api/running-system/dept/tree',
		lazyTree: '/api/running-system/dept/lazy-tree',
	},
	dict: {
		list: '/api/running-system/dict/list',
		parentList: '/api/running-system/dict/parent-list',
		childList: '/api/running-system/dict/child-list',
		remove: '/api/running-system/dict/remove',
		submit: '/api/running-system/dict/submit',
		detail: '/api/running-system/dict/detail',
		tree: '/api/running-system/dict/tree',
		allTree: '/api/running-system/dict/all-tree',
		dictionary: '/api/running-system/dict/dictionary',
	},
	topmenu: {
		list: '/api/running-system/topmenu/list',
		remove: '/api/running-system/topmenu/remove',
		submit: '/api/running-system/topmenu/submit',
		detail: '/api/running-system/topmenu/detail',
		grant: '/api/running-system/topmenu/grant',
	},
	menu: {
		list: '/api/running-system/menu/list',
		lazyList: '/api/running-system/menu/lazy-list',
		lazyMenuList: '/api/running-system/menu/lazy-menu-list',
		menuList: '/api/running-system/menu/menu-list',
		tree: '/api/running-system/menu/tree',
		remove: '/api/running-system/menu/remove',
		detail: '/api/running-system/menu/detail',
		submit: '/api/running-system/menu/submit',
		topMenu: '/api/running-system/menu/top-menu',
		routes: '/api/running-system/menu/routes',
		buttons: '/api/running-system/menu/buttons',
		roleTreeKeys: '/api/running-system/menu/role-tree-keys',
		grantTree: '/api/running-system/menu/grant-tree',
		grantTopTree: '/api/running-system/menu/grant-top-tree',
		topTreeKeys: '/api/running-system/menu/top-tree-keys',
	},
	role: {
		list: '/api/running-system/role/list',
		grant: '/api/running-system/role/grant',
		submit: '/api/running-system/role/submit',
		remove: '/api/running-system/role/remove',
		detail: '/api/running-system/role/detail',
		stop: '/api/running-system/role/stop',
		tree: '/api/running-system/role/tree',
		treeById: '/api/running-system/role/tree-by-id',
	},
	region: {
		allTree: '/api/running-system/region/all-tree',
	},
	demos: {
		page: '/api/running-demo/demo/page',
	},
};
